name: 'meu_dbt_pdf'
version: '1.0.0'
config-version: 2

profile: 'meu_dbt_pdf'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  meu_dbt_pdf:
    # Configurações de materialização por pasta
    bronze:
      +materialized: table
    silver:
      +materialized: table
    gold:
      +materialized: table