meu_dbt_pdf:
  outputs:
    dev:
      type: mysql
      host: localhost
      user: root
      password: amanda
      port: 3306
      dbname: analytics
      schema: dbt_schema
      threads: 4
      timeout_seconds: 300