version: 2

sources:
  - name: investimentos
    schema: analytics  # ou o nome do seu schema
    database: analytics  # ou o nome do seu banco
    tables:
      - name: fatura_jornada
      - name: fatura_jornada_small
      - name: fatura_redrex
      - name: fatura_redrex_small